# Generated by Django 3.1.2 on 2020-10-27 18:18

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_streetfood1'),
    ]

    operations = [
        migrations.CreateModel(
            name='dress1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('desc', models.TextField()),
                ('shop_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=1000)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=8)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=8)),
                ('geo_location', django.contrib.gis.db.models.fields.PointField(blank=True, db_index=True, null=True, srid=4326)),
                ('img', models.ImageField(max_length=2000000, upload_to='pices')),
                ('area', models.TextField()),
            ],
        ),
    ]
