# Generated by Django 3.1.2 on 2020-12-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_post2_post3_post4'),
    ]

    operations = [
        migrations.CreateModel(
            name='sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('desc', models.TextField()),
                ('shop_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=1000)),
                ('img', models.ImageField(max_length=2000000, upload_to='pices')),
                ('area', models.TextField()),
                ('sold_area', models.TextField()),
                ('customer_name', models.CharField(max_length=100)),
                ('sold_month', models.IntegerField(default=1)),
                ('sold_year', models.IntegerField(default=2020)),
            ],
        ),
    ]
