# Generated by Django 3.1.2 on 2020-12-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='organicveggies1',
            name='rating',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=8),
        ),
    ]
