# Generated by Django 3.1.2 on 2020-12-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_organicveggies1_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='dress1',
            name='rating',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='homeart1',
            name='rating',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='streetfood1',
            name='rating',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=8),
        ),
    ]
